export const ERROR = {
    ROOM_DOES_NOT_EXIST: 'ROOM DOES NOT EXIST',
    INVALID_RTPCAPABILITIES: 'INVALID RTPCAPABILITIES',
    CANNOT_CONSUME: 'CANNOT CONSUME',
    NO_CONSUMER_TRANSPORT: 'NO CONSUMER TRANSPORT'
}
